#!/usr/bin/env bash
# musicmaker one-command installer for a stock RunPod pod.
#
#   bash <(curl -sL https://raw.githubusercontent.com/vkfolio/MMaker/main/install.sh)
#
# Idempotent and resumable: re-running it updates the code and skips whatever is
# already installed. Everything lands on /workspace so it survives a pod restart.
#
# Flags:
#   --stub          skip ACE-Step; run the synthetic engine (fast, proves the pod)
#   --no-start      install only
#   --foreground    run in this shell instead of detaching
#   --port N        default 8000
#   --repo URL      default the one baked in below
set -euo pipefail

REPO="${MUSICMAKER_REPO:-https://github.com/vkfolio/MMaker.git}"
ROOT="${MUSICMAKER_ROOT:-/workspace}"
APP="$ROOT/MMaker"
PORT=8000
STUB=0
START=1
FOREGROUND=0

while [ $# -gt 0 ]; do
  case "$1" in
    --stub) STUB=1 ;;
    --no-start) START=0 ;;
    --foreground) FOREGROUND=1 ;;
    --port) PORT="$2"; shift ;;
    --repo) REPO="$2"; shift ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }

# ── sanity ────────────────────────────────────────────────────────────────────
if [ ! -d "$ROOT" ]; then
  echo "ERROR: $ROOT does not exist." >&2
  echo "On RunPod this is the network volume mount point. Attach a volume at" >&2
  echo "/workspace, or re-run with MUSICMAKER_ROOT=/some/other/path." >&2
  exit 1
fi

step "system packages"
if command -v apt-get >/dev/null 2>&1; then
  # fluidsynth + a SoundFont are what turn an uploaded MIDI file into audio;
  # ACE-Step takes no MIDI directly.
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
      git curl ffmpeg fluidsynth fluid-soundfont-gm libsndfile1 >/dev/null
  info "ok"
else
  info "no apt-get; skipping (make sure ffmpeg and fluidsynth exist)"
fi

step "code"
if [ -d "$APP/.git" ]; then
  git -C "$APP" pull --ff-only && info "updated $APP"
elif [ -d "$APP/server" ]; then
  info "using existing $APP (not a git checkout, leaving it alone)"
else
  git clone --depth 1 "$REPO" "$APP"
  info "cloned into $APP"
fi

step "python dependencies"
PIP="${PYTHON:-python} -m pip"
# A pip self-upgrade is nice but not worth failing the install over.
$PIP install -q --upgrade pip >/dev/null 2>&1 || info "pip self-upgrade skipped"
$PIP install -q -r "$APP/server/requirements.txt"
if [ "$STUB" = "0" ]; then
  $PIP install -q -r "$APP/server/requirements-pod.txt"
fi
info "ok"

# ── ACE-Step ──────────────────────────────────────────────────────────────────
ACESTEP_DIR="$ROOT/ACE-Step-1.5"
if [ "$STUB" = "1" ]; then
  step "ACE-Step"
  info "skipped (--stub)"
else
  step "ACE-Step 1.5"
  if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null
    export PATH="$HOME/.local/bin:$PATH"
  fi
  if [ -d "$ACESTEP_DIR/.git" ]; then
    info "already present at $ACESTEP_DIR"
  else
    git clone --depth 1 https://github.com/ace-step/ACE-Step-1.5.git "$ACESTEP_DIR"
  fi
  info "installing (this takes a few minutes)…"
  (cd "$ACESTEP_DIR" && uv sync)
  info "ok"
fi

# ── launcher ──────────────────────────────────────────────────────────────────
step "launcher"
TOKEN_FILE="$ROOT/.musicmaker_token"
if [ ! -f "$TOKEN_FILE" ]; then
  # RunPod proxy URLs are public. Generate a token rather than leaving the pod open.
  head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$TOKEN_FILE"
fi
TOKEN="$(cat "$TOKEN_FILE")"

cat > "$ROOT/run-musicmaker.sh" <<LAUNCHER
#!/usr/bin/env bash
# Generated by install.sh. Edit freely; re-running install.sh overwrites it.
set -euo pipefail
export PATH="\$HOME/.local/bin:\$PATH"
export MUSICMAKER_MODELS_DIR="$ROOT/models"
export MUSICMAKER_DATA_DIR="$ROOT/data"
export MUSICMAKER_PORT="$PORT"
export MUSICMAKER_API_TOKEN="\${MUSICMAKER_API_TOKEN:-$TOKEN}"
export ACESTEP_DIR="$ACESTEP_DIR"
export ACESTEP_URL="\${ACESTEP_URL:-http://127.0.0.1:8001}"
$([ "$STUB" = "1" ] && printf 'export MUSICMAKER_ENGINE=stub
export MUSICMAKER_STUB_MODELS=1')
cd "$APP/server"
exec ./start.sh
LAUNCHER
chmod +x "$ROOT/run-musicmaker.sh"
chmod +x "$APP/server/start.sh" 2>/dev/null || true
info "wrote $ROOT/run-musicmaker.sh"

POD_ID="${RUNPOD_POD_ID:-}"
if [ -n "$POD_ID" ]; then
  URL="https://${POD_ID}-${PORT}.proxy.runpod.net/?token=${TOKEN}"
else
  URL="http://localhost:${PORT}/?token=${TOKEN}"
fi

printf '\n\033[1mInstalled.\033[0m\n\n'
printf '  Open:    %s\n' "$URL"
printf '  Start:   %s\n' "$ROOT/run-musicmaker.sh"
printf '  Token:   %s  (saved in %s)\n' "$TOKEN" "$TOKEN_FILE"
[ "$STUB" = "1" ] && printf '\n  STUB MODE: output is a diagnostic tone, not music.\n'
printf '\n'

if [ "$START" != "1" ]; then
  exit 0
fi

if [ "$FOREGROUND" = "1" ]; then
  step "starting (foreground)"
  exec "$ROOT/run-musicmaker.sh"
fi

# Detached by default. Run in the foreground and the server is a child of this
# shell -- closing the RunPod web terminal, or letting it time out, kills it.
step "starting"
LOG="$ROOT/musicmaker.log"
PIDFILE="$ROOT/musicmaker.pid"

if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
  info "already running as PID $(cat "$PIDFILE"); restarting"
  kill "$(cat "$PIDFILE")" 2>/dev/null || true
  sleep 2
fi

nohup "$ROOT/run-musicmaker.sh" > "$LOG" 2>&1 &
echo $! > "$PIDFILE"
info "PID $(cat "$PIDFILE"), logging to $LOG"

# Don't just claim it started -- wait until it actually answers.
info "waiting for the engine to answer…"
READY=0
for i in $(seq 1 900); do
  BODY="$(curl -fsS "http://127.0.0.1:${PORT}/health" 2>/dev/null || true)"
  case "$BODY" in
    *'"status":"ready"'*|*'"status": "ready"'*) READY=1; break ;;
  esac
  if ! kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
    printf '
[1mThe server exited during startup.[0m Last lines of %s:

' "$LOG"
    tail -30 "$LOG"
    exit 1
  fi
  case "$BODY" in
    *downloading*) [ $((i % 30)) = 0 ] && info "still downloading weights (${i}s)…" ;;
  esac
  sleep 1
done

if [ "$READY" = "1" ]; then
  printf '
[1mRunning.[0m

'
  printf '  Open:    %s
' "$URL"
  printf '  Logs:    tail -f %s
' "$LOG"
  printf '  Stop:    kill $(cat %s)
' "$PIDFILE"
  printf '  Restart: %s

' "$ROOT/run-musicmaker.sh"
  if [ -n "$POD_ID" ]; then
    printf '  If that link 404s, the port is not exposed: RunPod console -> your pod
'
    printf '  -> Edit Pod -> Expose HTTP Ports -> add %s. The app itself is fine --
' "$PORT"
    printf '  "curl localhost:%s/health" from this terminal proves it.

' "$PORT"
  fi
else
  printf '
[1mStill not ready after 15 minutes.[0m Check: tail -f %s

' "$LOG"
fi
