"""Build the starter singer presets, and check they are actually different.

Where the clips come from: ACE-Step `text2music`. Unlike `cover`, it has full
freedom, so different captions really do produce different singers -- and the
result is model output, so nobody's voice is being used without their consent to
prove that voice selection works at all.

What this proves, and it is the thing gates 2 and 3 both failed on: a preset
selects a singer only if

    within(one preset, different seeds)  <<  between(different presets)

Captions on the `cover` path scored 0.60x and 0.77x -- no separation, the
"preset" selected nothing. SoulX's reference clip is a different mechanism
entirely: the timbre is copied from audio rather than described in words. If
this comes out well above 1.0, the voice library is real.
"""

from __future__ import annotations

import itertools
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app import voicebuild, voices                       # noqa: E402
from app.engines.acestep import AceStepEngine            # noqa: E402
from app.engines.soulx import SoulXSinger                # noqa: E402
from app.score import Note                               # noqa: E402
from app import lyrics as lyr                            # noqa: E402

# The words the generated clips sing. Kept simple and known, because the whole
# point of the cheap route is that we say what was sung instead of transcribing.
CLIP_WORDS = "hold me close and don't let go tonight"

PRESETS = [
    ("aria",  "Aria",  "solo female vocal, bright and clear, pop, a cappella, "
                       "no instruments, dry close mic"),
    ("juno",  "Juno",  "solo male vocal, warm and low, soul, a cappella, "
                       "no instruments, dry close mic"),
    ("wren",  "Wren",  "solo female vocal, breathy and soft, folk, a cappella, "
                       "no instruments, dry close mic"),
]

# What the presets get tested on: a plain rising phrase, nothing clever.
MELODY = [(67, 0.5), (69, 0.5), (71, 0.5), (72, 1.0), (71, 0.5), (69, 0.5), (67, 1.5)]
TEST_WORDS = "sing a little song for me"


def timbre(path: Path) -> np.ndarray:
    """MFCC statistics as a rough voice fingerprint.

    A proxy for a speaker embedding, not a speaker embedding. Trust the ratio
    between conditions, not the absolute numbers.
    """
    import librosa
    y, _ = librosa.load(str(path), sr=24000, mono=True)
    rms = librosa.feature.rms(y=y, hop_length=512)[0]
    m = librosa.feature.mfcc(y=y, sr=24000, n_mfcc=20, hop_length=512)
    keep = rms > max(1e-4, float(np.median(rms)) * 0.5)
    if keep.sum() > 4 and keep.shape[0] >= m.shape[1]:
        m = m[:, keep[:m.shape[1]]]
    return np.concatenate([m.mean(axis=1), m.std(axis=1)])


def distance(a, b) -> float:
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    return float(1.0 - np.dot(a, b) / (na * nb)) if na > 1e-9 and nb > 1e-9 else float("nan")


def main():
    out = Path("/workspace/gate/voices")
    out.mkdir(parents=True, exist_ok=True)
    ace = AceStepEngine()

    print("building presets\n")
    built = []
    for vid, label, caption in PRESETS:
        clip = out / f"{vid}.wav"
        if not clip.exists():
            t0 = time.time()
            ace.text2music(clip, caption,
                           lyrics="[verse]\n" + CLIP_WORDS + "\n" + CLIP_WORDS,
                           duration=30.0, seed=4242)
            print(f"  {label:6} generated in {time.time() - t0:4.0f}s")
        try:
            info = voicebuild.add(
                clip, label, CLIP_WORDS, voice_id=vid, builtin=True,
                description=f"Generated by ACE-Step: {caption.split(',')[0]}.",
                # Model output, not a person. Recorded plainly so the library
                # never implies a human agreed to something they did not.
                agreement="Synthetic voice generated by ACE-Step 1.5 XL; no human "
                          "singer is involved and no personal likeness is used.",
                recorded=True)
        except Exception as exc:                                  # noqa: BLE001
            print(f"  {label:6} FAILED to register: {exc}")
            continue
        print(f"     {info['label']}: {info['description'][:70]}")
        built.append(vid)

    if len(built) < 2:
        print("\nnot enough presets built to compare")
        return 1

    print("\nsinging the same phrase with each, twice, on different seeds")
    singer = SoulXSinger()
    notes = []
    t = 0.0
    for pitch, length in MELODY:
        notes.append(Note(start=t, length=length, pitch=pitch)); t += length
    spread = lyr.distribute(notes, TEST_WORDS)
    for n, a in zip(notes, spread.notes):
        n.lyric, n.phonemes = a.lyric, a.phonemes

    vectors: dict[str, list] = {}
    for vid in built:
        vectors[vid] = []
        ref = voices.reference(vid)
        for seed in (11, 22):
            dest = out / f"sing_{vid}_{seed}.wav"
            t0 = time.time()
            singer.sing(dest, notes, 120, ref, seed=seed)
            vectors[vid].append(timbre(dest))
            print(f"  {vid:6} seed {seed:3}  {time.time() - t0:4.1f}s  {dest.name}")

    within, between = [], []
    for vid, vecs in vectors.items():
        within += [distance(a, b) for a, b in itertools.combinations(vecs, 2)]
    for a_id, b_id in itertools.combinations(vectors, 2):
        between += [distance(x, y) for x in vectors[a_id] for y in vectors[b_id]]

    w, b = float(np.mean(within)), float(np.mean(between))
    ratio = b / w if w else 0.0
    print("\n" + "=" * 58)
    print(f"  within  (same voice, different seeds) : {w:.4f}")
    print(f"  between (different voices)            : {b:.4f}")
    print(f"  ratio                                 : {ratio:.2f}x")
    print("\n  Captions on the cover path managed 0.60-0.77x -- no separation.")
    print("  Well above 1.0 here means the reference clip really does pick a")
    print("  singer, and the voice library is a real feature.")

    (out / "results.json").write_text(
        json.dumps({"within": w, "between": b, "ratio": ratio,
                    "voices": built}, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
